-- ================================================================
-- EcoCycle Backend - V1__init.sql
-- Schema inicial do PostgreSQL, gerado a partir das entidades JPA
-- (Semanas 1 a 4). Ordem das tabelas respeita as dependencias de FK.
-- ================================================================

-- ---------------------------------------------------------------
-- 1. users
-- ---------------------------------------------------------------
CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR(150) NOT NULL,
    apelido        VARCHAR(20)  NOT NULL,
    senha_hash     VARCHAR(255) NOT NULL,
    avatar         VARCHAR(20)  NOT NULL,
    ativo          BOOLEAN      NOT NULL,
    xp_total       INTEGER      NOT NULL,
    criado_em      TIMESTAMP    NOT NULL,
    atualizado_em  TIMESTAMP    NOT NULL,
    CONSTRAINT uk_users_email   UNIQUE (email),
    CONSTRAINT uk_users_apelido UNIQUE (apelido)
);

-- ---------------------------------------------------------------
-- 2. conteudos_educativos
-- ---------------------------------------------------------------
CREATE TABLE conteudos_educativos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo           VARCHAR(20)  NOT NULL,
    trilha           VARCHAR(30)  NOT NULL,
    titulo           VARCHAR(150) NOT NULL,
    corpo            TEXT         NOT NULL,
    ordem            INTEGER      NOT NULL,
    imagem_sugerida  VARCHAR(300),
    CONSTRAINT uk_conteudo_codigo UNIQUE (codigo)
);

-- ---------------------------------------------------------------
-- 3. quizzes (1:1 com conteudos_educativos)
-- ---------------------------------------------------------------
CREATE TABLE quizzes (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conteudo_educativo_id   BIGINT  NOT NULL,
    xp_recompensa           INTEGER NOT NULL,
    CONSTRAINT uk_quiz_conteudo_educativo UNIQUE (conteudo_educativo_id),
    CONSTRAINT fk_quiz_conteudo_educativo FOREIGN KEY (conteudo_educativo_id)
        REFERENCES conteudos_educativos (id)
);

-- ---------------------------------------------------------------
-- 4. perguntas
-- ---------------------------------------------------------------
CREATE TABLE perguntas (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id    BIGINT  NOT NULL,
    enunciado  TEXT    NOT NULL,
    ordem      INTEGER NOT NULL,
    CONSTRAINT fk_pergunta_quiz FOREIGN KEY (quiz_id)
        REFERENCES quizzes (id)
);

-- ---------------------------------------------------------------
-- 5. alternativas
-- ---------------------------------------------------------------
CREATE TABLE alternativas (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pergunta_id BIGINT       NOT NULL,
    texto       VARCHAR(500) NOT NULL,
    letra       VARCHAR(1)   NOT NULL,
    correta     BOOLEAN      NOT NULL,
    CONSTRAINT fk_alternativa_pergunta FOREIGN KEY (pergunta_id)
        REFERENCES perguntas (id)
);

-- ---------------------------------------------------------------
-- 6. figurinhas
-- ---------------------------------------------------------------
CREATE TABLE figurinhas (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                 VARCHAR(20)  NOT NULL,
    nome                   VARCHAR(150) NOT NULL,
    tipo                   VARCHAR(10)  NOT NULL,
    conteudo_educativo_id  BIGINT,
    identificador_scan     VARCHAR(100),
    descricao              VARCHAR(500) NOT NULL,
    ordem                  INTEGER      NOT NULL,
    CONSTRAINT uk_figurinha_codigo UNIQUE (codigo),
    CONSTRAINT fk_figurinha_conteudo_educativo FOREIGN KEY (conteudo_educativo_id)
        REFERENCES conteudos_educativos (id)
);

-- ---------------------------------------------------------------
-- 7. figurinhas_usuario
-- ---------------------------------------------------------------
CREATE TABLE figurinhas_usuario (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT    NOT NULL,
    figurinha_id      BIGINT    NOT NULL,
    desbloqueada_em   TIMESTAMP NOT NULL,
    CONSTRAINT uk_figurinha_usuario UNIQUE (user_id, figurinha_id),
    CONSTRAINT fk_figurinha_usuario_user FOREIGN KEY (user_id)
        REFERENCES users (id),
    CONSTRAINT fk_figurinha_usuario_figurinha FOREIGN KEY (figurinha_id)
        REFERENCES figurinhas (id)
);

-- ---------------------------------------------------------------
-- 8. conteudos_lidos
-- ---------------------------------------------------------------
CREATE TABLE conteudos_lidos (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT    NOT NULL,
    conteudo_educativo_id  BIGINT    NOT NULL,
    lido_em                TIMESTAMP NOT NULL,
    CONSTRAINT uk_conteudo_lido_user_conteudo UNIQUE (user_id, conteudo_educativo_id),
    CONSTRAINT fk_conteudo_lido_user FOREIGN KEY (user_id)
        REFERENCES users (id),
    CONSTRAINT fk_conteudo_lido_conteudo_educativo FOREIGN KEY (conteudo_educativo_id)
        REFERENCES conteudos_educativos (id)
);

-- ---------------------------------------------------------------
-- 9. quiz_resultados
-- ---------------------------------------------------------------
CREATE TABLE quiz_resultados (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT    NOT NULL,
    quiz_id                 BIGINT    NOT NULL,
    acertos                 INTEGER   NOT NULL,
    total_perguntas         INTEGER   NOT NULL,
    xp_concedido            BOOLEAN   NOT NULL,
    primeira_conclusao_em   TIMESTAMP NOT NULL,
    ultima_tentativa_em     TIMESTAMP NOT NULL,
    CONSTRAINT uk_quiz_resultado_user_quiz UNIQUE (user_id, quiz_id),
    CONSTRAINT fk_quiz_resultado_user FOREIGN KEY (user_id)
        REFERENCES users (id),
    CONSTRAINT fk_quiz_resultado_quiz FOREIGN KEY (quiz_id)
        REFERENCES quizzes (id)
);

-- ---------------------------------------------------------------
-- 10. pontos_coleta
-- ---------------------------------------------------------------
CREATE TABLE pontos_coleta (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                    VARCHAR(150) NOT NULL,
    endereco                VARCHAR(300) NOT NULL,
    latitude                DOUBLE PRECISION NOT NULL,
    longitude               DOUBLE PRECISION NOT NULL,
    horario_funcionamento   VARCHAR(200),
    ativo                   BOOLEAN NOT NULL
);

-- ---------------------------------------------------------------
-- 11. ponto_coleta_tipos_residuo (@ElementCollection de PontoColeta)
-- ---------------------------------------------------------------
CREATE TABLE ponto_coleta_tipos_residuo (
    ponto_coleta_id  BIGINT       NOT NULL,
    tipo_residuo     VARCHAR(100),
    CONSTRAINT fk_ponto_coleta_tipo_residuo FOREIGN KEY (ponto_coleta_id)
        REFERENCES pontos_coleta (id)
);

-- ---------------------------------------------------------------
-- Indices de apoio (colunas de FK usadas em buscas frequentes)
-- ---------------------------------------------------------------
CREATE INDEX idx_perguntas_quiz ON perguntas (quiz_id);
CREATE INDEX idx_alternativas_pergunta ON alternativas (pergunta_id);
CREATE INDEX idx_figurinha_usuario_user ON figurinhas_usuario (user_id);
CREATE INDEX idx_conteudo_lido_user ON conteudos_lidos (user_id);
CREATE INDEX idx_quiz_resultado_user ON quiz_resultados (user_id);
CREATE INDEX idx_ponto_coleta_tipo_residuo_fk ON ponto_coleta_tipos_residuo (ponto_coleta_id);
