-- ================================================================
-- EcoCycle Backend - V3__leitura_scanner.sql
-- Registro de cada chamada ao scanner, para acompanhar como o modelo
-- TFLite se comporta no uso real (ver mudancas no back-end para o
-- scanner com IA, 07/10/2026, secao opcional "registrar as leituras").
-- ================================================================

CREATE TABLE leitura_scanner (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id   BIGINT        NOT NULL,
    identificador VARCHAR(100) NOT NULL,
    confianca    DECIMAL(5,2)  NOT NULL,
    reconhecido  BOOLEAN       NOT NULL,
    manual       BOOLEAN       NOT NULL,
    criado_em    TIMESTAMP     NOT NULL,
    CONSTRAINT fk_leitura_scanner_usuario FOREIGN KEY (usuario_id)
        REFERENCES users (id)
);

CREATE INDEX idx_leitura_scanner_usuario ON leitura_scanner (usuario_id);
